sudo: true
language: bash
services: docker

addons:
  apt:
    packages:
      - docker-ce

env:
  - VERSION=4.4.5-tz DOCKERFILE_PATH="./Dockerfile" IMAGE_NAME="manios/nagios:$VERSION"

before_script:
  - ./hooks/post_checkout
  - ./hooks/pre_build
  
script:
  - travis_retry ./hooks/build

after_script:
  - echo "$DOCKER_PASSWORD" | docker login -u manios --password-stdin
  - docker push $IMAGE_NAME
  - docker push $IMAGE_NAME-armv6
  - docker push $IMAGE_NAME-armv7
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - ./hooks/post_push
  - docker images
  - docker logout

# vim:set et ts=2 sw=2:
